---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chaoguan.
--- DateTime: 2020/11/1 11:59
---

local AIEntry = require("AIDesigner.Base.AITask").AIEntry

---树的入口节点
---@class AI.Entry:AIEntry
local Entry = AIUtil.Class("Entry", AIEntry)

return Entry