---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/1/27 17:28
---

--package.cpath = package.cpath .. ';C:/Users/PC/.Rider2019.3/config/plugins/intellij-emmylua/classes/debugger/emmy/windows/x64/?.dll'
--local dbg = require('emmy_core')
--dbg.tcpConnect('localhost', 9966)

local testPrint = print
local function cusPrint(...)
    testPrint(...)
end

print = cusPrint

local AITreeMgr = require('Logic.AIDesigner.AITreeMgr')

Test = {}
Test._trees = {}
Test._host = CS.UnityEngine.GameObject("AITree")
Test._trees["Test"] = AITreeMgr.CreateTree("Test")

function Test.Variable()
    --Test._trees["Test"]:SetVariable("TTTTT", 10)
end

function Test.Update()
    for _, tree in pairs(Test._trees) do
        tree:Tick()
    end
end

